// <auto-generated />
using Exercise6v2.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Exercise6v2.DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220329175036_Schoolv2")]
    partial class Schoolv2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Exercise6v2.DataAccess.Model.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Oskar L.",
                            LastName = "Ottesen"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Sara",
                            LastName = "Nordmann"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Harald",
                            LastName = "Nordmann"
                        },
                        new
                        {
                            StudentId = 4,
                            FirstName = "Therese",
                            LastName = "Nordmann"
                        });
                });

            modelBuilder.Entity("Exercise6v2.DataAccess.Model.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SubjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            SubjectName = "dotNet Programming"
                        },
                        new
                        {
                            SubjectId = 2,
                            SubjectName = "Kalkulus"
                        },
                        new
                        {
                            SubjectId = 3,
                            SubjectName = "Data Security"
                        });
                });

            modelBuilder.Entity("SubjectStudent", b =>
                {
                    b.Property<int>("StudentsStudenId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectsSubjectId")
                        .HasColumnType("int");

                    b.HasKey("StudentsStudenId", "SubjectsSubjectId");

                    b.HasIndex("SubjectsSubjectId");

                    b.ToTable("SubjectStudent");

                    b.HasData(
                        new
                        {
                            StudentsStudenId = 1,
                            SubjectsSubjectId = 1
                        },
                        new
                        {
                            StudentsStudenId = 2,
                            SubjectsSubjectId = 1
                        },
                        new
                        {
                            StudentsStudenId = 3,
                            SubjectsSubjectId = 2
                        },
                        new
                        {
                            StudentsStudenId = 4,
                            SubjectsSubjectId = 2
                        });
                });

            modelBuilder.Entity("SubjectStudent", b =>
                {
                    b.HasOne("Exercise6v2.DataAccess.Model.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsStudenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exercise6v2.DataAccess.Model.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
